#!/bin/bash

if [[ ! -e .git ]]; then
    echo "No git repo found here."
    exit 1
fi

if [[ ! -e .gg.txt ]]; then
    touch .gg.txt
fi

echo "" >> .gg.txt
if [[ "$1" == "" ]]; then
    echo "# UNTRACKED" >> .gg.txt
    cat .gg.txt | grep -F -x -v -f - <(git ls-files --modified --others --exclude-standard) >> .gg.txt
else
    echo "# $1" >> .gg.txt
    if ! git show-ref --verify --quiet refs/heads/$1 ; then
        base=$(git rev-parse refs/heads/main)
    else
        base=$(git merge-base --fork-point @{u} refs/heads/$1)
    fi
    git diff-tree -r --name-only "refs/heads/$1" "$base" >> .gg.txt
fi
